version: '3.8'

services:
  api-gateway:
    build: .
    ports:
      - "8100:8000"
    environment:
      - USER_SERVICE_URL=http://user-service:8001
      - ORDER_SERVICE_URL=http://order-service:8002
      - PAYMENT_SERVICE_URL=http://payment-service:8003
      - NOTIFICATION_SERVICE_URL=http://notification-service:8004
      - PROVIDER_SERVICE_URL=http://provider-service:8005
      - REPAIR_SERVICE_URL=http://repair-service:8006
    depends_on:
      - user-service
      - order-service
      - payment-service
      - notification-service
      - provider-service
      - repair-service

  user-service:
    build: ./user_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://user:password@user-db:5432/userdb
    volumes:
      - ./user_service:/app
      - ./application:/app/application
    depends_on:
      - user-db

  order-service:
    build: ./order_service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://user:password@order-db:5432/orderdb
    volumes:
      - ./order_service:/app
      - ./application:/app/application
    depends_on:
      - order-db

  payment-service:
    build: ./payment_service
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://user:password@payment-db:5432/paymentdb
    volumes:
      - ./payment_service:/app
      - ./application:/app/application
    depends_on:
      - payment-db

  user-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=userdb
    ports:
      - "5433:5432"
    volumes:
      - userdb-data:/var/lib/postgresql/data

  order-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=orderdb
    ports:
      - "5434:5432"
    volumes:
      - orderdb-data:/var/lib/postgresql/data

  payment-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=paymentdb
    ports:
      - "5438:5432"
    volumes:
      - paymentdb-data:/var/lib/postgresql/data

  notification-service:
    build: ./notification_service
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=postgresql://user:password@notification-db:5432/notificationdb
    volumes:
      - ./notification_service:/app
      - ./application:/app/application
    depends_on:
      - notification-db

  notification-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=notificationdb
    ports:
      - "5435:5432"
    volumes:
      - notificationdb-data:/var/lib/postgresql/data

  provider-service:
    build: ./provider_service
    ports:
      - "8005:8005"
    environment:
      - DATABASE_URL=postgresql://user:password@provider-db:5432/providerdb
    volumes:
      - ./provider_service:/app
      - ./application:/app/application
    depends_on:
      - provider-db

  provider-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=providerdb
    ports:
      - "5436:5432"
    volumes:
      - providerdb-data:/var/lib/postgresql/data

  repair-service:
    build: ./repair_service
    ports:
      - "8006:8006"
    environment:
      - DATABASE_URL=postgresql://user:password@repair-db:5432/repairdb
    volumes:
      - ./repair_service:/app
      - ./application:/app/application
    depends_on:
      - repair-db

  repair-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=repairdb
    ports:
      - "5437:5432"
    volumes:
      - repairdb-data:/var/lib/postgresql/data

volumes:
  userdb-data:
  orderdb-data:
  notificationdb-data:
  providerdb-data:
  repairdb-data:
  paymentdb-data: