name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Clone the code
        uses: actions/checkout@v4

      - name: 🔑 Connect to the server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Se déplacer dans le répertoire du projet
            cd /var/www/QuickServe
            
            # Mettre à jour le code du dépôt
            git pull origin main
            
            # Installer les dépendances Python (si nécessaire)
            if [ -f "requirements.txt" ]; then
              echo "Installation des dépendances Python..."
              pip3 install -r requirements.txt
            fi
            
            # Mettre à jour les conteneurs Docker
            docker-compose down
            docker-compose up -d --build
